version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  web:
    build: .
    command: bash -lc "flask --app app.py run --host=0.0.0.0 --port=8000"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_CONTENT_LENGTH_MB=10
      - OCR_LANG=por+eng
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "8000:8000"
